alter table public.team_matching_teams
  add column if not exists needed_roles jsonb not null default '[]'::jsonb,
  add column if not exists work_style text,
  add column if not exists meeting_style text,
  add column if not exists interest_areas jsonb not null default '[]'::jsonb,
  add column if not exists personality_tags jsonb not null default '[]'::jsonb,
  add column if not exists skill_tags jsonb not null default '[]'::jsonb;

alter table public.team_matching_applications
  add column if not exists capability_appeal text,
  add column if not exists personality_tags jsonb not null default '[]'::jsonb,
  add column if not exists skill_tags jsonb not null default '[]'::jsonb,
  add column if not exists availability_note text,
  add column if not exists reject_reason text;

create table if not exists public.team_matching_member_score_events (
  id integer primary key generated by default as identity,
  member_id integer not null references public.team_matching_members(id) on delete cascade,
  event_type text not null,
  points numeric not null default 0,
  verified boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.team_matching_peer_reviews (
  id integer primary key generated by default as identity,
  team_id integer references public.team_matching_teams(id) on delete cascade,
  reviewer_id integer references public.team_matching_members(id) on delete set null,
  reviewee_id integer not null references public.team_matching_members(id) on delete cascade,
  participation integer not null check (participation between 1 and 5),
  sincerity integer not null check (sincerity between 1 and 5),
  collaboration integer not null check (collaboration between 1 and 5),
  communication integer not null check (communication between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create index if not exists idx_team_matching_score_events_member
  on public.team_matching_member_score_events(member_id);

create index if not exists idx_team_matching_peer_reviews_reviewee
  on public.team_matching_peer_reviews(reviewee_id);

grant select, insert, update, delete on public.team_matching_member_score_events to service_role;
grant select, insert, update, delete on public.team_matching_peer_reviews to service_role;

grant usage, select on sequence public.team_matching_member_score_events_id_seq to service_role;
grant usage, select on sequence public.team_matching_peer_reviews_id_seq to service_role;
