-- MAST team matching schema draft
-- Purpose:
--   Import the expiring Replit team-matching data into the existing Supabase
--   project without disturbing the promotion-check tables.
--
-- Notes:
--   1. Existing public.members remains the promotion/member source of truth.
--   2. team_matching_members preserves the Replit member ids exactly and can be
--      linked to public.members through mast_member_id after reconciliation.
--      The first migration intentionally does not add a foreign key to avoid
--      coupling this launch to the live promotion service tables.
--   3. API writes should happen through server-side functions with the service
--      role key. Do not expose service role keys in the browser.

create extension if not exists pgcrypto;

create or replace function public.team_matching_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Team-matching-only privileges.
grant usage on schema public to service_role;

create table if not exists public.team_matching_members (
  id integer primary key generated by default as identity,
  mast_member_id uuid,
  name text not null,
  school text not null,
  major text,
  generation integer,
  role text not null default 'member'
    check (role in ('member', 'admin', 'professor')),
  is_leader boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, school, generation)
);

drop trigger if exists team_matching_members_set_updated_at on public.team_matching_members;
create trigger team_matching_members_set_updated_at
before update on public.team_matching_members
for each row execute function public.team_matching_set_updated_at();

create table if not exists public.team_matching_contests (
  id integer primary key generated by default as identity,
  title text not null,
  organizer text,
  prize text,
  registration_period text,
  category text,
  description text,
  is_active boolean not null default true,
  link text,
  registration_deadline text,
  award_count text,
  max_team_size integer,
  duplicate_allowed boolean,
  has_presentation boolean,
  presentation_date text,
  hackathon_date text,
  linked_commercialization boolean,
  has_certificate boolean,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists team_matching_contests_set_updated_at on public.team_matching_contests;
create trigger team_matching_contests_set_updated_at
before update on public.team_matching_contests
for each row execute function public.team_matching_set_updated_at();

-- Replit stores these fields as display strings, not strict dates/numbers.
-- Keep this alter block so rerunning the schema fixes a table created by an
-- earlier draft before importing data.
alter table public.team_matching_contests
  alter column registration_deadline type text using registration_deadline::text,
  alter column award_count type text using award_count::text;

create table if not exists public.team_matching_teams (
  id integer primary key generated by default as identity,
  contest_id integer not null references public.team_matching_contests(id) on delete cascade,
  leader_id integer not null references public.team_matching_members(id) on delete restrict,
  required_members integer not null,
  current_members integer not null default 1,
  introduction text,
  prize_distribution text,
  status text not null default 'recruiting'
    check (status in ('recruiting', 'matched', 'closed')),
  closed_at timestamptz,
  award_result text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists team_matching_teams_set_updated_at on public.team_matching_teams;
create trigger team_matching_teams_set_updated_at
before update on public.team_matching_teams
for each row execute function public.team_matching_set_updated_at();

create table if not exists public.team_matching_team_members (
  id integer primary key generated by default as identity,
  team_id integer not null references public.team_matching_teams(id) on delete cascade,
  member_id integer not null references public.team_matching_members(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (team_id, member_id)
);

create table if not exists public.team_matching_applications (
  id integer primary key generated by default as identity,
  team_id integer not null references public.team_matching_teams(id) on delete cascade,
  applicant_id integer not null references public.team_matching_members(id) on delete cascade,
  message text,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  survey_purpose text,
  survey_intensity text,
  survey_role text,
  survey_experience text,
  survey_strengths text,
  survey_team_style text,
  leader_priority integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, applicant_id)
);

drop trigger if exists team_matching_applications_set_updated_at on public.team_matching_applications;
create trigger team_matching_applications_set_updated_at
before update on public.team_matching_applications
for each row execute function public.team_matching_set_updated_at();

create table if not exists public.team_matching_leader_applications (
  id integer primary key generated by default as identity,
  member_id integer not null references public.team_matching_members(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected')),
  message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.team_matching_leader_applications
  drop constraint if exists team_matching_leader_applications_member_id_key;

drop trigger if exists team_matching_leader_applications_set_updated_at on public.team_matching_leader_applications;
create trigger team_matching_leader_applications_set_updated_at
before update on public.team_matching_leader_applications
for each row execute function public.team_matching_set_updated_at();

create table if not exists public.team_matching_awards (
  id integer primary key generated by default as identity,
  team_id integer references public.team_matching_teams(id) on delete cascade,
  contest_id integer references public.team_matching_contests(id) on delete cascade,
  award_result text,
  created_at timestamptz not null default now()
);

create index if not exists idx_team_matching_members_name on public.team_matching_members(name);
create index if not exists idx_team_matching_members_mast_member on public.team_matching_members(mast_member_id);
create index if not exists idx_team_matching_contests_active on public.team_matching_contests(is_active);
create index if not exists idx_team_matching_teams_contest on public.team_matching_teams(contest_id);
create index if not exists idx_team_matching_teams_leader on public.team_matching_teams(leader_id);
create index if not exists idx_team_matching_teams_status on public.team_matching_teams(status);
create index if not exists idx_team_matching_applications_team on public.team_matching_applications(team_id);
create index if not exists idx_team_matching_applications_applicant on public.team_matching_applications(applicant_id);
create index if not exists idx_team_matching_applications_status on public.team_matching_applications(status);

alter table public.team_matching_members enable row level security;
alter table public.team_matching_contests enable row level security;
alter table public.team_matching_teams enable row level security;
alter table public.team_matching_team_members enable row level security;
alter table public.team_matching_applications enable row level security;
alter table public.team_matching_leader_applications enable row level security;
alter table public.team_matching_awards enable row level security;

grant select on public.team_matching_members to anon, authenticated;
grant select on public.team_matching_contests to anon, authenticated;
grant select on public.team_matching_teams to anon, authenticated;
grant select on public.team_matching_team_members to anon, authenticated;
grant select on public.team_matching_awards to anon, authenticated;

grant select, insert, update, delete on public.team_matching_members to service_role;
grant select, insert, update, delete on public.team_matching_contests to service_role;
grant select, insert, update, delete on public.team_matching_teams to service_role;
grant select, insert, update, delete on public.team_matching_team_members to service_role;
grant select, insert, update, delete on public.team_matching_applications to service_role;
grant select, insert, update, delete on public.team_matching_leader_applications to service_role;
grant select, insert, update, delete on public.team_matching_awards to service_role;
grant usage, select on sequence public.team_matching_members_id_seq to service_role;
grant usage, select on sequence public.team_matching_contests_id_seq to service_role;
grant usage, select on sequence public.team_matching_teams_id_seq to service_role;
grant usage, select on sequence public.team_matching_team_members_id_seq to service_role;
grant usage, select on sequence public.team_matching_applications_id_seq to service_role;
grant usage, select on sequence public.team_matching_leader_applications_id_seq to service_role;
grant usage, select on sequence public.team_matching_awards_id_seq to service_role;

drop policy if exists "read team matching members" on public.team_matching_members;
drop policy if exists "read active team matching contests" on public.team_matching_contests;
drop policy if exists "read team matching teams" on public.team_matching_teams;
drop policy if exists "read team matching team members" on public.team_matching_team_members;
drop policy if exists "read team matching awards" on public.team_matching_awards;

create policy "read team matching members"
on public.team_matching_members for select
to anon, authenticated
using (true);

create policy "read active team matching contests"
on public.team_matching_contests for select
to anon, authenticated
using (is_active = true);

create policy "read team matching teams"
on public.team_matching_teams for select
to anon, authenticated
using (true);

create policy "read team matching team members"
on public.team_matching_team_members for select
to anon, authenticated
using (true);

create policy "read team matching awards"
on public.team_matching_awards for select
to anon, authenticated
using (true);
