-- MAST 팀 매칭: 관리자 기능 확장 마이그레이션
-- 실행 전: 기존 supabase_team_matching_schema.sql 가 적용되어 있어야 합니다.
-- Supabase SQL Editor 에서 이 파일 전체를 실행하세요.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. 공지사항
-- ---------------------------------------------------------------------------
create table if not exists public.team_matching_announcements (
  id integer primary key generated by default as identity,
  tag text not null default '공지',
  tag_tone text not null default 'notice'
    check (tag_tone in ('notice', 'event', 'tip')),
  title text not null,
  body text,
  published_at timestamptz not null default now(),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists team_matching_announcements_set_updated_at on public.team_matching_announcements;
create trigger team_matching_announcements_set_updated_at
before update on public.team_matching_announcements
for each row execute function public.team_matching_set_updated_at();

create index if not exists idx_team_matching_announcements_published
  on public.team_matching_announcements (is_published, published_at desc);

-- ---------------------------------------------------------------------------
-- 2. 관리자 발송 알림 (브로드캐스트 또는 개별)
-- ---------------------------------------------------------------------------
create table if not exists public.team_matching_notifications (
  id integer primary key generated by default as identity,
  member_id integer references public.team_matching_members(id) on delete cascade,
  type text not null default 'notice'
    check (type in ('notice', 'application_result', 'application_pending', 'leader_application_result')),
  title text not null,
  body text not null default '',
  href text,
  created_at timestamptz not null default now()
);

create index if not exists idx_team_matching_notifications_member
  on public.team_matching_notifications (member_id, created_at desc);

create index if not exists idx_team_matching_notifications_created
  on public.team_matching_notifications (created_at desc);

-- ---------------------------------------------------------------------------
-- 3. 알림 읽음 (DB 알림 + 이벤트 알림 공통 키)
--    notification_key 예: db-12, application-5-accepted, pending-application-3
-- ---------------------------------------------------------------------------
create table if not exists public.team_matching_notification_reads (
  member_id integer not null references public.team_matching_members(id) on delete cascade,
  notification_key text not null,
  read_at timestamptz not null default now(),
  primary key (member_id, notification_key)
);

create index if not exists idx_team_matching_notification_reads_member
  on public.team_matching_notification_reads (member_id);

-- ---------------------------------------------------------------------------
-- RLS (읽기는 서버 service_role 로만; 클라이언트 직접 접근 없음)
-- ---------------------------------------------------------------------------
alter table public.team_matching_announcements enable row level security;
alter table public.team_matching_notifications enable row level security;
alter table public.team_matching_notification_reads enable row level security;

grant select, insert, update, delete on public.team_matching_announcements to service_role;
grant select, insert, update, delete on public.team_matching_notifications to service_role;
grant select, insert, update, delete on public.team_matching_notification_reads to service_role;

grant usage, select on sequence public.team_matching_announcements_id_seq to service_role;
grant usage, select on sequence public.team_matching_notifications_id_seq to service_role;

-- ---------------------------------------------------------------------------
-- 4. 초기 공지 (선택) — fixture 와 동일 내용
-- ---------------------------------------------------------------------------
insert into public.team_matching_announcements (tag, tag_tone, title, body, published_at, is_published)
select '공지', 'notice', '2026년 1기 팀 매칭 플랫폼 오픈',
  'MAST 팀 매칭 플랫폼이 정식 오픈되었습니다. 공모전 탐색부터 팀 모집, 지원 관리까지 한곳에서 이용해 보세요.',
  '2026-06-01'::timestamptz, true
where not exists (select 1 from public.team_matching_announcements limit 1);

insert into public.team_matching_announcements (tag, tag_tone, title, body, published_at, is_published)
select '이벤트', 'event', '팀 매칭 성공 사례 공유 이벤트',
  '팀 매칭을 통해 공모전에 참여한 사례를 공유해 주시면 소정의 기념품을 드립니다.',
  '2026-06-05'::timestamptz, true
where (select count(*) from public.team_matching_announcements) < 2;

insert into public.team_matching_announcements (tag, tag_tone, title, body, published_at, is_published)
select '팁', 'tip', '공모전 팀원 모집 시 프로필 작성 가이드',
  '지원 메시지와 설문을 성실히 작성할수록 팀장에게 좋은 인상을 줄 수 있습니다. 전공과 역할을 구체적으로 적어 주세요.',
  '2026-06-08'::timestamptz, true
where (select count(*) from public.team_matching_announcements) < 3;
